name: PvpSystem
version: '1.0-SNAPSHOT'
main: me.hasenzahn1.pvp.PvpSystem
api-version: '1.21'

commands:
  peaceful:
    description: "Command to make a player peaceful"
    usage: "/peaceful (player) <on/off>"
    aliases: ["friedlich"]
  deathhistory:
    description: "View a player's death history"
    usage: "/deathhistory <player> [page]"
    aliases: ["dh", "deaths"]

permissions:
  pvpsystem.commands.peaceful:
    description: "Allows using the /peaceful command"
    default: true
  pvpsystem.commands.peaceful.other:
    description: "Allows setting peaceful mode for other players"
    default: op
  pvpsystem.commands.deathhistory:
    description: "Allows viewing death history of players"
    default: op
  pvpsystem.commands.deathhistory.teleport:
    description: "Allows teleporting to death locations"
    default: op
  pvpsystem.commands.deathhistory.inventory:
    description: "Allows viewing death inventories"
    default: op
  pvpsystem.commands.deathhistory.reset:
    description: "Allows restoring inventory and XP from deaths"
    default: op