name: PvpSystem
version: '1.0-SNAPSHOT'
main: me.hasenzahn1.pvp.PvpSystem
api-version: '1.21'

commands:
  peaceful:
    description: "Command to make a player peaceful"
    usage: "/peaceful (player) <on/off>"
    aliases: ["friedlich"]
  pvplookup:
    description: "Search for specific entries"
    usage: "/pvplookup args"
  deathhistory:
    description: "Search for deaths of players"
    usage: "/deathhistory <player>"
